-- Nerfing federation expansion -- 
NDefines.NCountry.TRIBE_SETTLE_ADM_COST = 250
NDefines.NCountry.TRIBE_SETTLE_DIP_COST = 250
NDefines.NCountry.TRIBE_SETTLE_MIL_COST = 250
NDefines.NCountry.TRIBE_MIGRATION_MIL_COST = 150
NDefines.NCountry.COHESION_FEDERATION_MEMBER_WRONG_CULTURE = 0.04
NDefines.NCountry.COHESION_FEDERATION_MEMBER_CORRECT_CULTURE = 0.08
NDefines.NCountry.COHESION_FEDERATION_MEMBER_STRONGER = -0.50
NDefines.NCountry.COHESION_FEDERATION_MEMBER_STRONGER_WRONG_CULTURE = -1.00
NDefines.NCountry.COHESION_FEDERATION_SAME_CULTURE_MEMBERS_BONUS_NUMBER = 3
NDefines.NCountry.COHESION_FEDERATION_SAME_CULTURE_MEMBERS_BONUS_MODIFIER = 0.8
NDefines.NCountry.COHESION_NEIGHBOURING_COLONIZER = 0.25
NDefines.NCountry.COHESION_FEDERATION_ADVANCEMENT = -0.05
-- Nerfing faction switch --
NDefines.NCountry.PS_FACTION_BOOST = 400